# Generated by Django 5.1.3 on 2024-12-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0002_remove_counsellor_user_remove_customuser_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="counsellor_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counsellorname", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="registration_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
