# Generated by Django 5.1.3 on 2024-12-06 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration_data",
            name="password",
        ),
    ]
