# Generated by Django 5.1.3 on 2024-12-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_registration_data_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="counsellor_data",
        ),
        migrations.RemoveField(
            model_name="registration_data",
            name="username",
        ),
        migrations.AddField(
            model_name="registration_data",
            name="email",
            field=models.EmailField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name="registration_data",
            name="password",
            field=models.CharField(default=False, max_length=20),
        ),
    ]
