# Generated by Django 5.1.3 on 2024-12-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_delete_counsellor_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration_data",
            name="email",
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name="registration_data",
            name="password",
            field=models.CharField(max_length=20),
        ),
    ]
