# Generated by Django 5.1.3 on 2024-12-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_registration_data_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration_data",
            name="type",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
