# Generated by Django 5.1.3 on 2024-12-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_registration_data_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="test_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testid", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50)),
                ("result", models.CharField(max_length=50)),
                ("date", models.DateField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="stressassessmentresponse",
            name="email",
        ),
        migrations.RemoveField(
            model_name="stressassessmentresponse",
            name="name",
        ),
    ]
