# Generated by Django 5.1.3 on 2024-12-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_alter_test_data_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointement_data",
            name="appointmentid",
        ),
        migrations.RemoveField(
            model_name="appointement_data",
            name="counsellorid",
        ),
        migrations.RemoveField(
            model_name="appointement_data",
            name="result",
        ),
        migrations.RemoveField(
            model_name="appointement_data",
            name="userid",
        ),
        migrations.AlterField(
            model_name="appointement_data",
            name="address",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="appointement_data",
            name="date",
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name="appointement_data",
            name="status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="appointement_data",
            name="time",
            field=models.TimeField(max_length=50),
        ),
    ]
