# Generated by Django 5.1.3 on 2025-01-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_remove_appointement_data_appointmentid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration_data",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="registration_data",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration_data",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="registration_data",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
