# Generated by Django 5.1.3 on 2025-01-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_test_data_date_alter_test_data_result_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="counsellor_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counsellorid", models.CharField(max_length=50)),
                ("counsellorname", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=50)),
            ],
        ),
    ]
